# This workflow lints and tests the client code.
# On push events to the main branch, it deploys the code to production.

name: Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 15.x

jobs:
  # Build, lint, and test the code.
  check:
    name: Client
    strategy:
      matrix:
        target: [build, lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install --immutable
      - run: yarn run ${{ matrix.target }}

  # On push to main, deploy to production
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [check]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}
      - working-directory: client
        run: yarn install --immutable
      - uses: Fooji/create-aws-profile-action@v1
        with:
          profile: goggle
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: make deploy-client
