# This workflow runs Terraform.
# On pull request events, this workflow will run `terraform init`, `terraform fmt`, and `terraform plan`.
# On push events to the main branch, `terraform apply` will be executed.

name: Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TERRAFORM_VERSION: 0.14.6

defaults:
  run:
    working-directory: terraform

jobs:
  # Checks that all Terraform configuration files adhere to a canonical format
  lint:
    name: Lint Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - run: terraform fmt -check

  # Generates an execution plan for Terraform
  plan:
    name: Plan Infrastructure
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: Fooji/create-aws-profile-action@v1
        with:
          profile: goggle
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: terraform init
      - run: terraform plan

  # On push to main, build or change infrastructure according to Terraform configuration files
  apply:
    name: Apply Infrastructure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [lint, plan]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: Fooji/create-aws-profile-action@v1
        with:
          profile: goggle
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: terraform init
      - run: terraform apply
